name: ticketing-v4-nodejs
services:

  client-gateway:
    build:
      context: .
      dockerfile: apps/client-gateway/Dockerfile.dev
    image: ticketing-v4-client-gateway-js
    container_name: ticketing-v4-client-gateway-js
    depends_on:
      auth:
        condition: service_started
    env_file:
      - ./apps/client-gateway/.env
    environment:
      AUTH_SERVICE: http://auth:3001/api
    command: sh -c "cd /app && npm exec -- nx run-many -t build -p common,errors && npm exec -- nx daemon --start && npm exec -- nx serve client-gateway"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.dev
    image: ticketing-v4-auth-js
    container_name: ticketing-v4-auth-js
    depends_on:
      auth-mongo:
        condition: service_healthy
    env_file:
      - ./apps/auth/.env
    environment:
      MONGO_URI: mongodb://auth-mongo:27017/auth
    command: sh -c "cd /app && npm exec -- nx run-many -t build -p common,errors && npm exec -- nx daemon --start && npm exec -- nx serve auth"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"

  auth-mongo:
    image: mongo:7.0
    container_name: ticketing-v4-auth-mongo-js
    environment:
      MONGO_INITDB_DATABASE: auth
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    volumes:
      - auth-mongo-data:/data/db

volumes:
  auth-mongo-data:
