FROM node:24-alpine

WORKDIR /app

# workspace metadata first (better cache)
COPY package.json package-lock.json tsconfig.base.json tsconfig.json ./
COPY apps/auth/package.json apps/auth/package.json
COPY libs/common/package.json libs/common/package.json
COPY libs/errors/package.json libs/errors/package.json

RUN npm install

# now bring sources
COPY apps/auth apps/auth
COPY libs/common libs/common
COPY libs/errors libs/errors

WORKDIR /app/apps/auth
CMD ["sh", "-c", "cd /app && npm exec -- nx run-many -t build -p common,errors && npm exec -- nx serve auth"]
