export const ENV_KEYS = {
  PORT: 'PORT',
  AUTH_SERVICE: 'AUTH_SERVICE',
  TICKETS_SERVICE: 'TICKETS_SERVICE',
  ORDERS_SERVICE: 'ORDERS_SERVICE',
  JWT_KEY: 'JWT_KEY',
} as const;

export const DI_TOKENS = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  TICKETS_SERVICE: 'TICKETS_SERVICE',
  ORDERS_SERVICE: 'ORDERS_SERVICE',
} as const;
