FROM node:24-alpine

WORKDIR /app

# workspace metadata first (better cache)
COPY package.json package-lock.json tsconfig.base.json tsconfig.json ./
COPY apps/client-gateway/package.json apps/client-gateway/package.json
COPY libs/common/package.json libs/common/package.json
COPY libs/errors/package.json libs/errors/package.json

RUN npm install

# now bring sources
COPY apps/client-gateway apps/client-gateway
COPY libs/common libs/common
COPY libs/errors libs/errors

WORKDIR /app/apps/client-gateway
CMD ["npm", "run", "dev"]
