export const NATS_JETSTREAM_MODULE_OPTIONS = Symbol(
  'NATS_JETSTREAM_MODULE_OPTIONS'
);
export const NATS_JETSTREAM_CONNECTION = Symbol('NATS_JETSTREAM_CONNECTION');
export const NATS_JETSTREAM_CLIENT = Symbol('NATS_JETSTREAM_CLIENT');
